version: '3.7'
services:
  backend:
    container_name: hello-service
    image: node:14.15.1
    command: npm run start
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3001:3001"
    environment:
      HOST: 0.0.0.0

networks:
  default:
    external:
      name: grader60